version: 3

tasks:
  docker-build:
    cmds:
      - docker build -t meteor .
  docker-run:
    cmds:
      - docker run --rm -p 8080:8080 meteor
  build:
    cmds:
      - go build -o bin/app cmd/meteor/main.go
  run:
    cmds:
      - task build
      - ./bin/app